// Generated by BallsReader (Rust but Java Syntax)

const RANDOM_CONSTANT: u64 = 34548945;

fn main() {
	print!("Hello, Rust. Your syntax is now fixed :)\n");
	let aInt: u32 = 32;
	let anotherInt = 32;
	print!("32 + 32 = {}", aInt+anotherInt);
}

fn imConcerned(bruh: &str) -> u64 {
	123456
}
