// Generated by BallsReader (Rust but Java Syntax)

fn main() {
	print!("Hello, Rust. Your syntax is now fixed :)\n");
	let aInt: u32 = 32;
	let anotherInt = 32;
	print!("32 + 32 = {}", aInt+anotherInt);
}
