package me.hydos.just;

import me.hydos.just.type.Constant;
import me.hydos.just.type.Function;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

public class RustFile {

    public final String name;
    public final List<Function> functions;
    public final List<Constant> constants;

    public RustFile(String name) {
        this.name = name;
        this.functions = new ArrayList<>();
        this.constants = new ArrayList<>();
    }

    public void write() {
        try {
            try (BufferedWriter writer = Files.newBufferedWriter(Paths.get(this.name))) {
                writer.write("// Generated by BallsReader (Rust but Java Syntax)\n");

                for (Constant constant : this.constants) {
                    constant.write(writer);
                }

                for (Function function : this.functions) {
                    function.write(writer);
                }
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
